### ISSUE TITLE
Streams got out of sync between janus and cm-janus

### ISSUE THREAD

**Issue by njam** [cargomedia/cm-janus#192] opened 2016-03-02 08:02 UTC
cm-janus has 4:
```
$ curl -H 'Server-key: FqVWLUzZE8swExCfTn5y' 'http://10.68.236.78:8100/status'
[{"id":"12c345d9-6972-43ad-b15b-b3c04b7aae1f","channelName":"chAWrPhiHWpDCruw7FEh3w__"},{"id":"f1c3d67d-9a24-40eb-a46c-fda83d4335bf","channelName":"t-4Kup5TdFgQfp8WUOPkBQ__"},{"id":"d4841083-a092-41c2-958b-8435cefde9da","channelName":"8.XRV2XlHP.k5nyBk211Mw__"},{"id":"760657ce-e68d-4d6f-b10c-788b680eada3","channelName":"cqNh3rZ2iNk.D8yg65oqoA__"}]
```

janus has 0:
![screen shot 2016-03-02 at 08 55 17](https://cloud.githubusercontent.com/assets/360800/13453999/85412b38-e054-11e5-8fbc-9b89bbdd6d7d.png)

This happened on 2016-03-02 between 05:25 and 07:55 UTC.
The studio-agent repeatedly tried to re-create a mountpoint during that time:
![screen shot 2016-03-02 at 08 55 09](https://cloud.githubusercontent.com/assets/360800/13454021/b85bd9d2-e054-11e5-8b0d-af4f3baaba1c.png)

@tomaszdurka @vogdb can you investigate?
Here's the log: https://drive.google.com/open?id=0B-gYrWtYkIpmejBZaUJNM0w3aWM

**Comment by vogdb** [comment] 2016-03-02 09:09
According to the logs it had started on `2016-03-02 05:45:29.462`. The root cause was that we couldn't publish a stream.
```
Error: Cannot publish: Stream{"id":"40a3a7d6-ca02-43ec-bfba-c499a24d2473"} for Plugin{"id":1355522179,"type":"janus.plugin.cm.rtpbroadcast"} error: cm-api error: 500 - Internal server error

    at /usr/lib/node_modules/cm-janus/lib/janus/plugin/streaming.js:81:13
    at tryCatcher (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/util.js:11:23)
    at /usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/promise.js:670:18)
    at Async._drainQueue (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/async.js:129:16)
    at Async._drainQueues (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/async.js:139:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/cm-janus/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by njam** [comment] 2016-03-02 09:28
But this shouldn't result in out-of-sync streams, right?

**Comment by vogdb** [comment] 2016-03-02 09:29
Yep. I'm preparing now a detailed research.

**Comment by vogdb** [comment] 2016-03-02 10:05
Btw why we have shows at 5.47am UTC? Is that ok?

**Comment by njam** [comment] 2016-03-02 10:18
It was a test show, running from bulldog2 in Basel :)

**Comment by tomaszdurka** [comment] 2016-03-02 10:45
Oh this is still buggy. I will analyse again if the queueing for adding/removal is sufficient.

Important log pieces:
```
2016-03-02 05:58:58.244 INFO - Added Plugin{"id":1258294074,"type":"janus.plugin.cm.rtpbroadcast"} for Session{"id":3502223475}
2016-03-02 05:58:58.368 INFO - Removed Plugin{"id":1258294074,"type":"janus.plugin.cm.rtpbroadcast"}
2016-03-02 05:58:58.418 INFO - Added Stream{"id":"12c345d9-6972-43ad-b15b-b3c04b7aae1f"} for Plugin{"id":1258294074,"type":"janus.plugin.cm.rtpbroadcast"}
2016-03-02 05:58:59.035 INFO - Storing Stream{"id":"12c345d9-6972-43ad-b15b-b3c04b7aae1f"} for Plugin{"id":1258294074,"type":"janus.plugin.cm.rtpbroadcast"}
2016-03-02 05:59:53.164 INFO - http-client request http://localhost:8300/janus/3502223475/1258294074 { janus: 'detach', transaction: 'vzk5cgx6sv' }
2016-03-02 05:59:53.166 WARN - Stream stop failed [Error: http-client error: No such session 3502223475]
```

cm-janus cannot remove streams - we are calling janus http server and it fails with "No such session". This should be probably rescued and removed from local storage anyway.

Alternatively we can use new cm-janus client and simply detach existing plugin.

**Comment by tomaszdurka** [comment] 2016-03-02 10:55
1. We got into invalid state - this is something we have been aware of and happens in high concurrency of add/remove plugin - it will be fixed by streaming-plugin action queuing.
2. There is a bug where cm cannot invalidate streams. This should be addressed in https://github.com/cargomedia/cm-janus/issues/195.

**Comment by vogdb** [comment] 2016-03-02 11:10
It's quite a clew here. "No such session" happens cause session is destroyed before detach. It happens due to uncaught error from `cm-api-client.publish`. There are also plenty of other errors. Most of them are fixed in 0.6.0.

**Comment by tomaszdurka** [comment] 2016-03-02 11:12
Same mechanism (http-client).

**Comment by njam** [comment] 2016-03-21 09:58
@tomaszdurka so everything is covered? closeable?

**Comment by tomaszdurka** [comment] 2016-03-21 09:59
Yes, let's say it's good.

**Closed by tomaszdurka** 2016-03-21 09:59 UTC
Labels: bug, ready
