### ISSUE TITLE
Plugin.removeStream() cannot forcefully remove stream

### ISSUE THREAD

**Issue by njam** [cargomedia/cm-janus#270] opened 2016-06-21 15:57 UTC
Trying to remove a "corrupt" stream with the `/stopStream` API.
The following code gets executed:
```js
          stream.plugin.removeStream()
            .then(function() {
              res.send({error: 'Stream stop failed. Stream was removed by force.'});
              next();
            })
```

The API responds with "Stream stop failed. Stream was removed by force.".
But the stream seems to not be removed. I.e. it is still returned on the `/status` API.

@vogdb @tomaszdurka can you investigate?

**Comment by vogdb** [comment] 2016-06-21 15:59
ok, will look into

**Comment by vogdb** [comment] 2016-06-22 11:31
Can't reproduce. Please give a link to logs if possible.

**Comment by njam** [comment] 2016-06-23 07:33
Tomasz told me you looked at this together, and showed you the logs. He told me you have an idea what could have happened, and will implement a workaround.

**Comment by vogdb** [comment] 2016-06-23 07:37
ehhm. I don't have an idea actually :) I just found two minor problems 271 and 272 while was looking into this.

**Comment by tomaszdurka** [comment] 2016-07-12 09:56
After forced-removal:
- verify plugin's stream was removed
- verify stream was removed from streams
- otherwise log fatal error for debugging

@vogdb can you implement this in separate ticket?

**Comment by kris-lab** [comment] 2016-08-09 12:25
@tomaszdurka @vogdb what is the status here?

**Comment by vogdb** [comment] 2016-08-09 12:39
It should not happen anymore

**Comment by kris-lab** [comment] 2016-08-09 12:58
Is it closable then?

**Comment by vogdb** [comment] 2016-08-09 13:15
If @tomaszdurka does not have any objections

**Comment by tomaszdurka** [comment] 2016-08-11 08:38
Let's close it... Btw one-time problem we tried to *solve* with this never happened again.

**Closed by tomaszdurka** 2016-08-11 08:38 UTC
Labels: bug, ready
